# Generated by Django 3.2.2 on 2021-05-12 18:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=5, unique=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('desc_referenciada', models.TextField()),
                ('desc_especialidades', models.TextField()),
                ('telefone', models.CharField(max_length=15)),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', geography=True, srid=4326)),
            ],
        ),
    ]
