# Generated by Django 3.2.2 on 2021-05-13 12:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_alter_area1_localizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area1',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='area1',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='geom'),
        ),
    ]
