# Generated by Django 3.2.2 on 2021-05-13 12:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_auto_20210513_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area1',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Localização'),
        ),
    ]
